### ISSUE TITLE
When the window is small, the media file usually goes over its container.

### ISSUE THREAD

**Issue by lolgreatjcc** [lolgreatjcc/Readdit#100]
For example, 
the video below is larger than its post container.
![image](https://user-images.githubusercontent.com/87067973/142422260-6cba2541-8163-4d4c-acf1-57fcaaa035e7.png)

**Comment by TYRPRO** [comment]
Fixed this by ensuing that the width of the content relies on the parent container using max-width:inherit; . Fixed in PR #109
