### ISSUE TITLE
Non-admins and non-moderators are able to access pages they aren't supposed to have access to.

### ISSUE THREAD

**Issue by lolgreatjcc** [lolgreatjcc/Readdit#116]

**Comment by lolgreatjcc** [comment]
Example:
Admin Home page
![image](https://user-images.githubusercontent.com/87067973/142622781-af34ab2b-7063-48ab-83f3-717a798595bb.png)
Manage Users page
![image](https://user-images.githubusercontent.com/87067973/142622825-b92ee959-ce64-4030-83cc-79e5a7a6f022.png)

**Comment by Klyntar5** [comment]
Resolved in #134
