### ISSUE TITLE
Backend: Backend API routes don't have proper response. 

### ISSUE THREAD

**Issue by lolgreatjcc** [lolgreatjcc/Readdit#86]
The routes don't send proper error responses for different contingencies.
Furthermore, most routes just use status 500 for all errors.
[REST API Best Practices](https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/)

**Comment by TYRPRO** [comment]
Added new responses (wrong password, file size too large etc) to error response. Fixed in PR #126.
