### ISSUE TITLE
Frontend: Homepage Media doesn't display properly

### ISSUE THREAD

**Issue by lolgreatjcc** [lolgreatjcc/Readdit#87]
![image](https://user-images.githubusercontent.com/87067973/142355307-74772f81-c2a5-4c93-949f-090ea4f272de.png)

**Comment by Klyntar5** [comment]
I have fixed this issue, it was a result of a syntax error from the baseURL variable.
![image](https://user-images.githubusercontent.com/87118990/142430774-d1dd1cba-b0bd-47ae-9114-618a99ce615a.png)
