### ISSUE TITLE
Admins are able to delete themselves in admin tools. Will be fixed by Adam once core is complete.

### ISSUE THREAD

**Issue by lolgreatjcc** [lolgreatjcc/Readdit#96]

**Comment by Klyntar5** [comment]
I fixed it by disabling the buttons in the front end if it checks that you're the logged in user
Fixed in pull request #99

**Comment by lolgreatjcc** [comment]
Make sure that there's also a backend check.

**Comment by lolgreatjcc** [comment]
Don't trust user input.
"Outside is Jungle" - an ESDE Teacher :)

**Comment by Klyntar5** [comment]
> Make sure that there's also a backend check.

But users will need to be able to delete their own accounts in their profile page. That hasnt been implemented yet but I think we'll have to add it in CA2. I think it's perfectly fine for an admin to delete their own account, just not via the admin menu. If they want to do it, they should delete their account in profile or something. We can implement this either in CA2 or I can add it now.

**Comment by lolgreatjcc** [comment]
> 
> 
> > Make sure that there's also a backend check.
> 
> But users will need to be able to delete their own accounts in their profile page. That hasn't been implemented yet but I think we'll have to add it in CA2. I think it's perfectly fine for an admin to delete their own account, just not via the admin menu. If they want to do it, they should delete their account in profile or something. We can implement this either in CA2 or I can add it now.

I don't see the connection between **users** deleting themselves from the **profile** page and **admins** deleting themselves in the **admin** page having to do anything with making sure there's a check that admins aren't able to delete themselves from the **admin** page. But I digress, if you think the feature is complete then so be it.
