### ISSUE TITLE
Some API calls in the frontend are still using the temporary user_id.

### ISSUE THREAD

**Issue by lolgreatjcc** [lolgreatjcc/Readdit#97]
Example:
The createPost.js still uses the temporary user_id, 2.
Leading to every post being created by user 2.
![image](https://user-images.githubusercontent.com/87067973/142377723-93dd8a8c-8236-447e-b006-12a286a3a11b.png)

**Comment by TYRPRO** [comment]
Reopened to comment. Fixed this issue by passing in the token for requests that needed user_id, and the backend gets the user_id from the token, Fixed in PR #103 and #104.
